---
- name: Prepare for molecule scenarios
  hosts: all
  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Ensure cron.d exists in docker containers
      ansible.builtin.file:
        state: 'directory'
        path: '/etc/cron.d'
        mode: 0777
